server:
  addr: :4181
  metrics: true
  healthz: true
  readyz: true
  pprof: true
logger:
  # 日志存放路径，关闭控制台日志后，日志文件存放位置
  # path: temp/logs
  # 日志输出，file：文件，default：命令行，其他：命令行
  stdout: default #控制台日志，启用后，不输出到文件
  # 日志等级, trace, debug, info, warn, error, fatal
  level: info
  # 日志格式 json json格式
  json: false
database:
  driver: sqlite
  source: 'nsqauthd.db'
  name: nsqauthd
  timeout: 10s
ttl: 3600