// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth": {
            "get": {
                "description": "authenticate",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "authenticate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "secret",
                        "name": "secret",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "remote_ip",
                        "name": "remote_ip",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "tls",
                        "name": "tls",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.AuthResp"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthAccount": {
            "type": "object",
            "properties": {
                "channels": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "topic": {
                    "type": "string"
                }
            }
        },
        "dto.AuthResp": {
            "type": "object",
            "properties": {
                "authorizations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AuthAccount"
                    }
                },
                "identity": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "ttl": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.0.1",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "nsqauthd API",
	Description:      "nsqauthd接口文档",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
